name: Build SEED AC2

on:
  workflow_dispatch:
    inputs:
      debug:
        description: 'Enable debug output'
        type: boolean
        default: false

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup environment
      run: sudo bash -c 'bash <(curl -s https://build-scripts.immortalwrt.org/init_build_environment.sh)'
      
    - name: Build firmware
      run: |
        ./scripts/feeds update -a
        ./scripts/feeds install -a
        
        # 静默配置
        make menuconfig <<CONFIG_EOF
        /Target: MediaTek Ralink ARM
        /Subtarget: Filogic 8x0 (MT798x) 
        /Device: BeeconMini SEED AC2
        CONFIG_EOF
        
        if ${{ inputs.debug }}; then
          make -j$(nproc) V=sc 2>&1 | tee full-build.log
        else
          make -j$(nproc) 2>&1 | grep -E "ERROR|error:|Building|Creating" | tee build-summary.log
        fi
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: firmware-${{ github.run_id }}
        path: bin/targets/mediatek/filogic/
